# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089f1575d35073238b0350bf636b772c541beff8d2a25f217522949fc1184a1900af169ddba7a1707f8ac9cd79af6b7a28db6fb2fd57cf39de00e8100ab7890d

test:
  secret_key_base: 083c098c74f6e07d6b7f7791e9791caadee3f9403ec24e13bb7f6334b1026f887ce2f0bfb261a2ba07730f5ba7877d8a6ff5284786db7c08d419a6048c25220b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
